@host = localhost
@port = 5842

@url = http://{{host}}:{{port}}

### Help
GET {{url}}/help

#### Topics(帖子)
### List
GET {{url}}/topic

@tid = 1
### Info
GET {{url}}/topic/{{tid}}

# Error
@tid = 2
### Create
PUT {{url}}/topic/{{tid}}

### Delete
DELETE {{url}}/topic/{{tid}}

### Update
POST {{url}}/topic/{{tid}}
Content-Type: application/json

{
    "UpdateCron": "@every 2m"
}

### View
GET {{url}}/view/{{tid}}