# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [amd64, arm64]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get version
      id: get_version
      run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Set up arch
      run: |
        if [ "${{ matrix.arch }}" == "arm64" ]; then
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
        fi

    - name: Build
      run: |
        if [ "${{ matrix.arch }}" == "arm64" ]; then
          GOARCH=arm64 go build -v -o ngamm-${{ matrix.os }}-arm64-${{ env.VERSION }} ./...
        else
          GOARCH=amd64 go build -v -o ngamm-${{ matrix.os }}-amd64-${{ env.VERSION }} ./...
        fi

    - name: Test
      run: go test -v ./...
